default: &default
  adapter: postgresql
  encoding: unicode
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: simpleadmin_application_development

test:
  <<: *default
  database: simpleadmin_application_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
